name: lint

on: push

jobs:
  super-lint:
    name: Basic checks
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v2
      - name: install package
        run: npm install
      - name: Check lints
        run: npm run lint
